# Generated by Django 5.1.4 on 2024-12-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('fee_by_month', models.FloatField()),
                ('due_month', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('stocks', models.IntegerField()),
            ],
        ),
    ]
