# Generated by Django 5.1.4 on 2025-01-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_loans_stocks_loans_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stocks', models.IntegerField()),
                ('loans', models.FloatField()),
                ('fees', models.FloatField()),
                ('fine', models.FloatField()),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
