# Generated by Django 5.1.4 on 2025-01-05 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_loans_remaining_value_meetingentries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingentries',
            name='loan_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='website.loans'),
            preserve_default=False,
        ),
    ]
