# Generated by Django 5.1.4 on 2025-01-05 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_meetingentries_loan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingentries',
            name='loan_id',
        ),
        migrations.AddField(
            model_name='temporaryentries',
            name='loan_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='website.loans'),
            preserve_default=False,
        ),
    ]
