# Generated by Django 5.1.4 on 2025-01-05 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_meeting_id_meetingentries_meeting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetings',
            old_name='loans',
            new_name='loans_made',
        ),
        migrations.AddField(
            model_name='loans',
            name='meeting',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='website.meetings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loans',
            name='member',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='website.members'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingentries',
            name='loan',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='website.loans'),
            preserve_default=False,
        ),
    ]
