# Generated by Django 5.1.4 on 2025-01-20 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_temporaryentries_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='website.members'),
        ),
        migrations.AlterField(
            model_name='meetingentries',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingentries', to='website.members'),
        ),
        migrations.AlterField(
            model_name='temporaryentries',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporaryentries', to='website.members'),
        ),
    ]
