# Generated by Django 5.1.4 on 2025-01-20 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_loans_member_alter_meetingentries_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.members'),
        ),
        migrations.AlterField(
            model_name='meetingentries',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.loans'),
        ),
    ]
