# Generated by Django 5.1.4 on 2025-01-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_loans_member_alter_meetingentries_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='loans_paid',
            field=models.FloatField(default=0),
        ),
    ]
