# Generated by Django 5.1.4 on 2025-01-22 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_meetings_loans_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetings',
            old_name='fine',
            new_name='fines',
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.meetings')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.members')),
            ],
        ),
    ]
