# Generated by Django 5.1.4 on 2025-01-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_rename_fine_meetings_fines_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
