# Generated by Django 5.1.4 on 2025-01-22 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_fine_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='website.members'),
        ),
    ]
