# Generated by Django 5.1.4 on 2025-01-26 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_fine_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('type', models.CharField(max_length=20)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.meetings')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund', to='website.members')),
            ],
        ),
    ]
