# Generated by Django 5.1.4 on 2025-01-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_fundmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundmovement',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.meetings'),
        ),
        migrations.AlterField(
            model_name='fundmovement',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund', to='website.members'),
        ),
        migrations.AlterField(
            model_name='fundmovement',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
