# Generated by Django 5.1.4 on 2025-01-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_fundmovement_meeting_alter_fundmovement_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='fund',
            field=models.FloatField(default=0),
        ),
    ]
